import {
  Customer,
  Expense,
  InventoryItem,
  MonthlyMetric,
  Order,
  Poster,
  PrintJob,
  Shipment,
  Supplier,
} from '../models/erp.models';

const now = '2026-05-24T09:00:00.000Z';

export const mockCustomers: Customer[] = [
  {
    id: 'cus-001',
    createdAt: now,
    updatedAt: now,
    name: 'Aarav Mehta',
    phone: '+91 98765 21010',
    email: 'aarav.mehta@example.com',
    city: 'Delhi',
    source: 'Offline',
    lifetimeValue: 18450,
    orderCount: 9,
  },
  {
    id: 'cus-002',
    createdAt: now,
    updatedAt: now,
    name: 'Nisha Kapoor',
    phone: '+91 99880 12344',
    email: 'nisha.kapoor@example.com',
    city: 'Gurugram',
    source: 'Website',
    lifetimeValue: 12600,
    orderCount: 5,
  },
  {
    id: 'cus-003',
    createdAt: now,
    updatedAt: now,
    name: 'Canvas & Co Cafe',
    phone: '+91 90909 11223',
    email: 'orders@canvascafe.example',
    city: 'Noida',
    source: 'Offline',
    lifetimeValue: 53200,
    orderCount: 14,
  },
  {
    id: 'cus-004',
    createdAt: now,
    updatedAt: now,
    name: 'Priya Sethi',
    phone: '+91 98111 22009',
    email: 'priya.sethi@example.com',
    city: 'Jaipur',
    source: 'Marketplace',
    lifetimeValue: 8700,
    orderCount: 3,
  },
];

export const mockPosters: Poster[] = [
  {
    id: 'pst-001',
    createdAt: now,
    updatedAt: now,
    sku: 'KP-MIN-18X24',
    title: 'Minimal Mountain Line Art',
    category: 'Minimal',
    tags: ['line-art', 'nature', 'home'],
    size: '18 x 24 in',
    price: 799,
    stock: 42,
    soldThisMonth: 38,
    active: true,
  },
  {
    id: 'pst-002',
    createdAt: now,
    updatedAt: now,
    sku: 'KP-BOL-12X18',
    title: 'Bollywood Retro Collage',
    category: 'Pop Culture',
    tags: ['cinema', 'retro', 'gift'],
    size: '12 x 18 in',
    price: 599,
    stock: 18,
    soldThisMonth: 31,
    active: true,
  },
  {
    id: 'pst-003',
    createdAt: now,
    updatedAt: now,
    sku: 'KP-CUS-A3',
    title: 'Personalized Name Poster',
    category: 'Personalized',
    tags: ['custom', 'kids', 'name'],
    size: 'A3',
    price: 999,
    stock: 0,
    soldThisMonth: 24,
    active: true,
  },
  {
    id: 'pst-004',
    createdAt: now,
    updatedAt: now,
    sku: 'KP-TRV-A2',
    title: 'India Travel Grid',
    category: 'Travel',
    tags: ['travel', 'india', 'wall'],
    size: 'A2',
    price: 1199,
    stock: 11,
    soldThisMonth: 19,
    active: true,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    createdAt: now,
    updatedAt: now,
    name: 'Shree Paper Mart',
    contact: 'Manish Gupta',
    phone: '+91 93111 11122',
    category: 'Paper Rolls',
    outstanding: 18750,
  },
  {
    id: 'sup-002',
    createdAt: now,
    updatedAt: now,
    name: 'FrameCraft India',
    contact: 'Sonal Arora',
    phone: '+91 98989 45454',
    category: 'Frames',
    outstanding: 9200,
  },
  {
    id: 'sup-003',
    createdAt: now,
    updatedAt: now,
    name: 'Inkline Supplies',
    contact: 'Rajat Khanna',
    phone: '+91 98100 77770',
    category: 'Ink',
    outstanding: 0,
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: 'inv-001',
    createdAt: now,
    updatedAt: now,
    sku: 'MAT-PAPER-MATTE-24',
    name: 'Matte Paper Roll 24 inch',
    category: 'Paper Rolls',
    supplierId: 'sup-001',
    unit: 'roll',
    quantity: 7,
    reorderLevel: 6,
    unitCost: 2450,
    lastMovement: 'Consumed for ORD-1048',
  },
  {
    id: 'inv-002',
    createdAt: now,
    updatedAt: now,
    sku: 'MAT-INK-CYAN-1L',
    name: 'Cyan Ink 1L',
    category: 'Ink',
    supplierId: 'sup-003',
    unit: 'bottle',
    quantity: 3,
    reorderLevel: 5,
    unitCost: 1650,
    lastMovement: 'Purchase received',
  },
  {
    id: 'inv-003',
    createdAt: now,
    updatedAt: now,
    sku: 'MAT-FRM-BLK-A3',
    name: 'Black Frame A3',
    category: 'Frames',
    supplierId: 'sup-002',
    unit: 'piece',
    quantity: 56,
    reorderLevel: 20,
    unitCost: 190,
    lastMovement: 'Reserved for custom jobs',
  },
  {
    id: 'inv-004',
    createdAt: now,
    updatedAt: now,
    sku: 'MAT-PACK-TUBE',
    name: 'Poster Shipping Tube',
    category: 'Packaging Material',
    supplierId: 'sup-001',
    unit: 'piece',
    quantity: 14,
    reorderLevel: 25,
    unitCost: 38,
    lastMovement: 'Website shipments',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-1048',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1048',
    customerId: 'cus-001',
    customerName: 'Aarav Mehta',
    type: 'Custom Design',
    channel: 'Offline',
    status: 'Printing In Progress',
    priority: 'Rush',
    dueDate: '2026-05-25',
    total: 3499,
    paid: 1500,
    lines: [
      {
        description: 'Custom family collage poster',
        size: '24 x 36 in',
        quantity: 1,
        unitPrice: 3499,
        framing: 'Black frame',
      },
    ],
  },
  {
    id: 'ord-1049',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1049',
    customerId: 'cus-002',
    customerName: 'Nisha Kapoor',
    type: 'Ready-made',
    channel: 'Website',
    status: 'Ready for Shipping',
    priority: 'Normal',
    dueDate: '2026-05-24',
    total: 1598,
    paid: 1598,
    lines: [
      {
        posterId: 'pst-001',
        description: 'Minimal Mountain Line Art',
        size: '18 x 24 in',
        quantity: 2,
        unitPrice: 799,
        framing: 'No frame',
      },
    ],
  },
  {
    id: 'ord-1050',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1050',
    customerId: 'cus-003',
    customerName: 'Canvas & Co Cafe',
    type: 'Personalized',
    channel: 'Offline',
    status: 'Lamination',
    priority: 'High',
    dueDate: '2026-05-27',
    total: 9800,
    paid: 5000,
    lines: [
      {
        description: 'Cafe menu wall posters set',
        size: 'A2',
        quantity: 7,
        unitPrice: 1400,
        framing: 'Wood frame',
      },
    ],
  },
  {
    id: 'ord-1051',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1051',
    customerId: 'cus-004',
    customerName: 'Priya Sethi',
    type: 'Ready-made',
    channel: 'Marketplace',
    status: 'Delivered',
    priority: 'Normal',
    dueDate: '2026-05-23',
    total: 1199,
    paid: 1199,
    lines: [
      {
        posterId: 'pst-004',
        description: 'India Travel Grid',
        size: 'A2',
        quantity: 1,
        unitPrice: 1199,
        framing: 'No frame',
      },
    ],
  },
];

export const mockPrintJobs: PrintJob[] = [
  {
    id: 'job-501',
    createdAt: now,
    updatedAt: now,
    jobNo: 'JOB-501',
    orderId: 'ord-1048',
    orderNo: 'ORD-1048',
    customerName: 'Aarav Mehta',
    stage: 'Printing In Progress',
    priority: 'Rush',
    size: '24 x 36 in',
    material: 'Matte paper',
    estimatedCompletion: '2026-05-24 18:00',
    operator: 'Imran',
  },
  {
    id: 'job-502',
    createdAt: now,
    updatedAt: now,
    jobNo: 'JOB-502',
    orderId: 'ord-1050',
    orderNo: 'ORD-1050',
    customerName: 'Canvas & Co Cafe',
    stage: 'Lamination',
    priority: 'High',
    size: 'A2',
    material: 'Gloss paper',
    estimatedCompletion: '2026-05-25 13:00',
    operator: 'Simran',
  },
  {
    id: 'job-503',
    createdAt: now,
    updatedAt: now,
    jobNo: 'JOB-503',
    orderId: 'ord-1049',
    orderNo: 'ORD-1049',
    customerName: 'Nisha Kapoor',
    stage: 'Packaging',
    priority: 'Normal',
    size: '18 x 24 in',
    material: 'Poster stock',
    estimatedCompletion: '2026-05-24 16:00',
    operator: 'Vikram',
  },
];

export const mockShipments: Shipment[] = [
  {
    id: 'shp-301',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1049',
    customerName: 'Nisha Kapoor',
    carrier: 'Delhivery',
    trackingNo: 'DLV9218871',
    status: 'Packed',
    city: 'Gurugram',
    eta: '2026-05-26',
  },
  {
    id: 'shp-302',
    createdAt: now,
    updatedAt: now,
    orderNo: 'ORD-1051',
    customerName: 'Priya Sethi',
    carrier: 'Blue Dart',
    trackingNo: 'BD7701298',
    status: 'Delivered',
    city: 'Jaipur',
    eta: '2026-05-23',
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'exp-001',
    createdAt: now,
    updatedAt: now,
    date: '2026-05-20',
    category: 'Materials',
    vendor: 'Shree Paper Mart',
    amount: 28400,
    paymentMode: 'Bank Transfer',
    notes: 'Matte and gloss paper rolls',
  },
  {
    id: 'exp-002',
    createdAt: now,
    updatedAt: now,
    date: '2026-05-21',
    category: 'Packaging',
    vendor: 'Local Packaging Depot',
    amount: 4200,
    paymentMode: 'UPI',
    notes: 'Shipping tubes and labels',
  },
  {
    id: 'exp-003',
    createdAt: now,
    updatedAt: now,
    date: '2026-05-22',
    category: 'Utilities',
    vendor: 'Power Distribution',
    amount: 7650,
    paymentMode: 'Bank Transfer',
    notes: 'Monthly electricity advance',
  },
];

export const mockMonthlyMetrics: Array<
  MonthlyMetric & { id: string; createdAt: string; updatedAt: string }
> = [
  { id: 'met-jan', createdAt: now, updatedAt: now, month: 'Jan', revenue: 148000, expenses: 72000, orders: 96 },
  { id: 'met-feb', createdAt: now, updatedAt: now, month: 'Feb', revenue: 164000, expenses: 76000, orders: 108 },
  { id: 'met-mar', createdAt: now, updatedAt: now, month: 'Mar', revenue: 189000, expenses: 84000, orders: 124 },
  { id: 'met-apr', createdAt: now, updatedAt: now, month: 'Apr', revenue: 211000, expenses: 91000, orders: 139 },
  { id: 'met-may', createdAt: now, updatedAt: now, month: 'May', revenue: 236000, expenses: 97000, orders: 151 },
];
