-- Enable UUID generation extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. PosterCategory
CREATE TABLE IF NOT EXISTS "PosterCategory" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "name" TEXT UNIQUE NOT NULL
);

-- 2. Customer
CREATE TABLE IF NOT EXISTS "Customer" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "lifetimeValue" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "orderCount" INTEGER DEFAULT 0 NOT NULL
);

-- 3. Supplier
CREATE TABLE IF NOT EXISTS "Supplier" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "name" TEXT NOT NULL,
  "contact" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "outstanding" DOUBLE PRECISION DEFAULT 0 NOT NULL
);

-- 4. Poster
CREATE TABLE IF NOT EXISTS "Poster" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "sku" TEXT UNIQUE NOT NULL,
  "title" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "categoryId" UUID REFERENCES "PosterCategory"("id") ON DELETE SET NULL,
  "tags" TEXT[] NOT NULL,
  "size" TEXT NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "stock" INTEGER DEFAULT 0 NOT NULL,
  "soldThisMonth" INTEGER DEFAULT 0 NOT NULL,
  "active" BOOLEAN DEFAULT TRUE NOT NULL
);

-- 5. Order
CREATE TABLE IF NOT EXISTS "Order" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "orderNo" TEXT UNIQUE NOT NULL,
  "customerId" UUID NOT NULL REFERENCES "Customer"("id") ON DELETE RESTRICT,
  "customerName" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "status" TEXT DEFAULT 'Draft' NOT NULL,
  "priority" TEXT DEFAULT 'Normal' NOT NULL,
  "dueDate" TIMESTAMP WITH TIME ZONE NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "paid" DOUBLE PRECISION DEFAULT 0 NOT NULL
);

-- 6. OrderItem
CREATE TABLE IF NOT EXISTS "OrderItem" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "orderId" UUID NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "posterId" UUID REFERENCES "Poster"("id") ON DELETE SET NULL,
  "description" TEXT NOT NULL,
  "size" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unitPrice" DOUBLE PRECISION NOT NULL,
  "framing" TEXT DEFAULT 'No frame' NOT NULL
);

-- 7. InventoryItem
CREATE TABLE IF NOT EXISTS "InventoryItem" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "sku" TEXT UNIQUE NOT NULL,
  "name" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "supplierId" UUID NOT NULL REFERENCES "Supplier"("id") ON DELETE RESTRICT,
  "unit" TEXT NOT NULL,
  "quantity" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "reorderLevel" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "unitCost" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "lastMovement" TEXT
);

-- 8. InventoryMovement
CREATE TABLE IF NOT EXISTS "InventoryMovement" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "inventoryItemId" UUID NOT NULL REFERENCES "InventoryItem"("id") ON DELETE CASCADE,
  "quantity" DOUBLE PRECISION NOT NULL,
  "type" TEXT NOT NULL,
  "reference" TEXT,
  "notes" TEXT
);

-- 9. Expense
CREATE TABLE IF NOT EXISTS "Expense" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "category" TEXT NOT NULL,
  "vendor" TEXT NOT NULL,
  "supplierId" UUID REFERENCES "Supplier"("id") ON DELETE SET NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "paymentMode" TEXT NOT NULL,
  "notes" TEXT
);

-- 10. ProductionJob
CREATE TABLE IF NOT EXISTS "ProductionJob" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "jobNo" TEXT UNIQUE NOT NULL,
  "orderId" UUID UNIQUE NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "orderNo" TEXT NOT NULL,
  "customerName" TEXT NOT NULL,
  "stage" TEXT NOT NULL,
  "priority" TEXT DEFAULT 'Normal' NOT NULL,
  "size" TEXT NOT NULL,
  "material" TEXT NOT NULL,
  "estimatedCompletion" TIMESTAMP WITH TIME ZONE,
  "operator" TEXT
);

-- 11. Shipment
CREATE TABLE IF NOT EXISTS "Shipment" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "orderId" UUID UNIQUE NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "orderNo" TEXT NOT NULL,
  "customerName" TEXT NOT NULL,
  "carrier" TEXT NOT NULL,
  "trackingNo" TEXT UNIQUE NOT NULL,
  "status" TEXT DEFAULT 'Packed' NOT NULL,
  "city" TEXT NOT NULL,
  "eta" TIMESTAMP WITH TIME ZONE
);

-- 12. Coupon
CREATE TABLE IF NOT EXISTS "Coupon" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "code" TEXT UNIQUE NOT NULL,
  "discount" DOUBLE PRECISION NOT NULL,
  "active" BOOLEAN DEFAULT TRUE NOT NULL
);

-- 13. PartnerInvestment
CREATE TABLE IF NOT EXISTS "PartnerInvestment" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "partnerName" TEXT NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "date" TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 14. Invoice
CREATE TABLE IF NOT EXISTS "Invoice" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "invoiceNo" TEXT UNIQUE NOT NULL,
  "orderId" UUID NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "amount" DOUBLE PRECISION NOT NULL,
  "pdfUrl" TEXT
);

-- 15. ArtworkUpload
CREATE TABLE IF NOT EXISTS "ArtworkUpload" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "orderId" UUID NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE,
  "fileName" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL
);

-- 16. DashboardSnapshot
CREATE TABLE IF NOT EXISTS "DashboardSnapshot" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "revenue" DOUBLE PRECISION NOT NULL,
  "expenses" DOUBLE PRECISION NOT NULL,
  "orders" INTEGER NOT NULL,
  "pendingPrintJobs" INTEGER NOT NULL,
  "inventoryAlerts" INTEGER NOT NULL,
  "profit" DOUBLE PRECISION NOT NULL
);

-- 17. Settings
CREATE TABLE IF NOT EXISTS "Settings" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "companyName" TEXT DEFAULT 'KPrints' NOT NULL,
  "currency" TEXT DEFAULT 'INR' NOT NULL,
  "setupCompleted" BOOLEAN DEFAULT FALSE NOT NULL,
  "demoMode" BOOLEAN DEFAULT FALSE NOT NULL
);
